Mesd\ApyDataGridTestBundle\Entity\Another:
    type: entity
    table: another
    repositoryClass: Mesd\ApyDataGridTestBundle\Entity\AnotherRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        # exampleArray:
        #     type: array
        #     nullable: true
        # exampleSimpleArray:
        #     type: simple_array
        #     nullable: true
        # exampleJsonArray:
        #     type: json_array
        #     nullable: true
        # exampleObject:
        #     type: object
        #     nullable: true
        exampleBoolean:
            type: boolean
            nullable: true
        exampleInteger:
            type: integer
            nullable: true
        exampleSmallInt:
            type: smallint
            nullable: true
        exampleBigInt:
            type: bigint
            nullable: true
        exampleString:
            type: string
            nullable: true
            length: 255
        exampleText:
            type: text
            nullable: true
        exampleDatetime:
            type: datetime
            nullable: true
        # exampleDatetimeTz:
        #     type: datetimetz
        #     nullable: true
        exampleDate:
            type: date
            nullable: true
        exampleTime:
            type: time
            nullable: true
        exampleDecimal:
            type: decimal
            nullable: true
        exampleFloat:
            type: float
            nullable: true
        # exampleBlob:
        #     type: blob
        #     nullable: true
        # exampleGuid:
        #     type: guid
        #     nullable: true
    lifecycleCallbacks: {  }
