mesd_apy_data_grid_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MesdApyDataGridTestBundle:Default:index }

mesd_apy_data_grid_test_grid:
    pattern:  /
    defaults: { _controller: MesdApyDataGridTestBundle:Default:myGrid }

MesdApyDataGridTestBundle_everything:
    resource: "@MesdApyDataGridTestBundle/Resources/config/routing/everything.yml"
    prefix:   /everything
