<?php

namespace Mesd\ApyDataGridTestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnotherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnotherRepository extends EntityRepository
{
}
